services:
  web:
    build: ToListApp
    ports:
      - "80:80"
  app:
    build: .
    environment:
      - DB_URL=postgresql://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DATABASE}
      - PG_USER=postgres
      - PG_PASSWORD=4417YRM^4#
      - PG_HOST=localhost
      - PG_PORT=5432
      - PG_DATABASE=postgres