FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .



ENV PYTHONUNBUFFERED=1


ENV DB_URL="postgresql://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE}"

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "90"]
